// Builds the pool seed migration from the owner's list (scripts/mtg/data/my_collection.json),
// enriched with Scryfall Oracle data: exact text, cost, type, colors and image.
// Counts, German copies, the owner's short text and notes are kept as written.
//
//   node scripts/mtg/build-seed.mjs <oracle-cards.jsonl.gz> > supabase/migrations/20261008120100_magic_seed.sql
//
// Cards that do not match keep the photo text and status, with no image.
import { readFileSync } from 'node:fs';
import { readBulk, isPaperCard, toCatalogRow } from './scryfall.mjs';

if (!process.argv[2]) {
  console.error('usage: node scripts/mtg/build-seed.mjs <oracle-cards.jsonl.gz> > supabase/migrations/20261008120100_magic_seed.sql');
  process.exit(1);
}

const pool = JSON.parse(readFileSync(new URL('./data/my_collection.json', import.meta.url), 'utf8')).cards;

// German-only titles, resolved by hand with a Scryfall `lang:de` search on 2026-10-08.
const ALIASES = {
  'Kollision der Elemente (Collision of Elements)': 'Clash of Elements',
  'Widerlegung des Schicksals': 'Refute Destiny',
  'Staerke des Stiers': "Bull's Strength",
};

const norm = (s) => s.normalize('NFKD').replace(/[̀-ͯ]/g, '').replace(/’/g, "'").toLowerCase().trim();

/** "Eisiger Empfang (Icy Reception)" -> try "Icy Reception", then "Eisiger Empfang". */
function candidates(name) {
  if (ALIASES[name]) return [ALIASES[name]];
  const m = name.match(/^(.*?)\s*\((.*?)\)$/);
  if (!m) return [name];
  return /^(basic|full art)$/i.test(m[2]) ? [m[1]] : [m[2], m[1]];
}

const index = new Map();
for await (const card of readBulk(process.argv[2])) {
  if (!isPaperCard(card)) continue;
  const key = norm(card.name);
  if (!index.has(key)) index.set(key, card);
  const front = card.name.split(' // ')[0];
  if (front !== card.name && !index.has(norm(front))) index.set(norm(front), card);
}

const sql = (v) => {
  if (v === null || v === undefined) return 'null';
  if (Array.isArray(v)) return `array[${v.map(sql).join(', ')}]::text[]`;
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};

const unmatched = [];
const values = pool.map((p) => {
  const hit = candidates(p.name).map((c) => index.get(norm(c))).find(Boolean);
  const variant = p.name.match(/\((full art)\)$/i)?.[1];
  const note = [p.note, variant && 'Full-art printing.'].filter(Boolean).join(' ') || null;
  if (!hit) unmatched.push(p.name);
  const row = hit
    ? (({ oracle_id, name, colors, type_line, mana_cost, mana_value, power_toughness, oracle_text, image_url, scryfall_uri }) => ({
        oracle_id, name, colors, type_line, mana_cost, mana_value, power_toughness, oracle_text, image_url, scryfall_uri, status: 'scryfall',
      }))(toCatalogRow(hit))
    : {
        oracle_id: null,
        name: p.name,
        colors: p.colors,
        type_line: p.type,
        mana_cost: p.mana_cost,
        mana_value: p.mana_value,
        power_toughness: p.power_toughness,
        oracle_text: p.effect,
        image_url: null,
        scryfall_uri: null,
        status: p.status,
      };
  const cols = { ...row, name_de: p.name_de, owned_qty: p.owned_qty, copies_de: p.copies_de, short: p.short, note };
  return cols;
});

const COLUMNS = [
  'oracle_id', 'name', 'name_de', 'owned_qty', 'copies_de', 'colors', 'type_line', 'mana_cost', 'mana_value',
  'power_toughness', 'oracle_text', 'short', 'status', 'note', 'image_url', 'scryfall_uri',
];

console.log(`-- Seed for public.mtg_collection, generated by scripts/mtg/build-seed.mjs.
-- ${values.length} entries, ${values.reduce((n, v) => n + v.owned_qty, 0)} cards; ${values.length - unmatched.length} matched on Scryfall.
-- Not matched (photo text kept, status unchanged): ${unmatched.join('; ') || 'none'}.
-- Runs once: skipped when the pool already has rows, so it never doubles counts.
do $seed$
begin
  if exists (select 1 from public.mtg_collection) then
    return;
  end if;
  insert into public.mtg_collection (${COLUMNS.join(', ')}) values
${values.map((v) => `    (${COLUMNS.map((c) => sql(v[c])).join(', ')})`).join(',\n')};
end
$seed$;`);
console.error(`seed: ${values.length} entries, unmatched: ${unmatched.length} -> ${unmatched.join(', ')}`);
